AllCops:
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'configure']
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 100
  Exclude:
    - spec/**/*
    - seeyoucup.gemspec
Style/CommentedKeyword:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Performance/UnfreezeString:
  Enabled: false
